services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5241
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    ports:
      - "5241:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whattoplaynow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d whattoplaynow"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data: 