services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5241
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    ports:
      - "5241:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: whattoplaynow
    volumes:
      - mongo_data:/data/db

networks:
  appnet:
    driver: bridge

volumes:
  mongo_data: 