services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5241
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    ports:
      - "5241:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  appnet:
    driver: bridge 