services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5241
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    ports:
      - "5241:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whattoplaynow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  mongo_data:
  postgres_data: 